### ISSUE TITLE
Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector.defineClass" is null

### ISSUE THREAD

**Issue by irinamagdici** [kieve/solo-gjm#3]
Hi!  I surely must be doing something wrong, cuz I can't get past the first step - I'm seeing this: https://imgur.com/a/qQ0hcb5
I've proxy-music (built with mvn > .jar is in target folder) on same level with gjm-converter (built with mvn > .jar is in target folder). What I'm doing right now is go in gjm-converter  > target folder and running "java -jar --module-path "C:\Program Files\javafx-sdk-11.0.2\lib" --add-modules javafx.controls,javafx.fxml gjm-converter-0.2-SNAPSHOT-jar-with-dependencies.jar" 

Can you set me on the right path and let me know what I should be doing tho? Or is this a real issue?  It seems it's not finding the jaxb classes (which I'm seeing they live in proxy-music > target folder). Should I copy something from proxy-music in the gjm-converter > target folder maybe?

Thanks for any feedback and congrats for doing this anyway!

============
Error shown in log window: Failed to parse file.
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector.defineClass" is null
----
error in command prompt:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 25, 2021 1:00:52 AM org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
[.........]
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.lang.Class.getMethod(Class.java:2195)
        at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector$3.run(Injector.java:165)
        at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector$3.run(Injector.java:161)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        ... 59 more

**Comment by kieve** [comment]
You have to run "patch-lib.bat" if you're attempting to run it as a module project. slf4j (the class in the command prompt error) won't load without it.
That said... you shouldn't have to do that. The "jar with dependencies" build should just run on its own without anything else specified.

You shouldn't have to copy anything. You just make sure the submodule is checked out with git.
Make sure you're using Java15 too.

Separately, I highly recommend running it using IntelliJ, I have no idea how to get it to run using the command line.
That, or run the "createWinExe.bat" and install / run the binary form.

jaxb is a pain in the ass to get loading correctly. Especially since it was removed from the JVM. So I never bothered with it outside the maven build.
